image: "registry.gitlab.com/byzantine-lab/go-tangerine/ci-testbed:latest"

before_script:
  - mkdir -p /go/src/github.com/tangerine-network
  - ln -s /builds/tangerine-network/go-tangerine /go/src/github.com/tangerine-network
  - cd /go/src/github.com/tangerine-network/go-tangerine

stages:
  - lint
  - test
  - docker

lint:
  stage: lint
  tags:
    - golang
  script:
    - go run build/ci.go lint

test:
  stage: test
  tags:
    - golang
  script:
    - make libbls
    - go run build/ci.go install
    - go run build/ci.go test -coverage

smoke:
  stage: test
  tags:
    - golang
  script:
    - ./build/setup_recovery_env.sh
    - make gtan
    - ./test/run_test.sh --smoke-test
    - ./build/fullnode-test.sh
    - pkill -15 -f gtan
    - ./test/run_test.sh --continue --smoke-test
    - ./build/recovery-test.sh


docker:
  only:
    - master
  stage: docker
  image: docker:stable
  services:
    - docker:dind
  variables:
    IMAGE: byzantinelab/go-tangerine
  tags:
    - golang
  script:
    - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE:latest .
    - docker push $IMAGE:latest
